# Generated by Django 4.0.4 on 2023-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(default='images/avatars/default.png', upload_to='images/avatars/'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='confirmemail',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterModelTable(
            name='avatar',
            table='avatar',
        ),
        migrations.AlterModelTable(
            name='confirmemail',
            table='confirm_email',
        ),
        migrations.AlterModelTable(
            name='follow',
            table='follow',
        ),
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
        migrations.AlterModelTable(
            name='reaction',
            table='reaction',
        ),
        migrations.AlterModelTable(
            name='tags',
            table='tags',
        ),
    ]
