# Generated by Django 3.2.20 on 2023-09-04 08:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='images/avatars/default.png', max_length=255, verbose_name='images/avatars/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(default='images/default.png', max_length=255, verbose_name='images/'),
        ),
    ]
