# Generated by Django 3.2.20 on 2023-09-04 09:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230904_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='avatar',
            name='images/avatars/',
            field=cloudinary.models.CloudinaryField(default='images/avatars/default.png', max_length=255, verbose_name='images'),
        ),
        migrations.AddField(
            model_name='image',
            name='images/',
            field=cloudinary.models.CloudinaryField(default='images/default.png', max_length=255, verbose_name='image'),
        ),
    ]
