# Generated by Django 3.2.20 on 2023-09-04 09:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20230904_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='images/avatars/',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='image',
            name='images/',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(default='images/default.png', max_length=255, verbose_name='images'),
        ),
    ]
