# Generated by Django 3.2.20 on 2023-09-04 14:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_avatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='default_y8l4fd.png', max_length=255, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_snkrnb.png', max_length=255, verbose_name='images'),
        ),
    ]
