# Generated by Django 3.2.20 on 2023-09-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20230904_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(default='images/avatars/default.png', upload_to='images/avatars/'),
        ),
    ]
