# Generated by Django 3.2.20 on 2023-09-04 14:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_avatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='images/avatars/default_y8l4fd.png', max_length=255, verbose_name='avatar'),
        ),
    ]
